name: SLACK_NOTIFICATION

on: 
  push:
    branches: 
      - 'v[0-9]+.[0-9]+'
      - master
    paths-ignore:
      - '**/#NORUN*'
    
jobs:
  SLACK_NOTIFICATION: 
    runs-on: ubuntu-latest
    
    steps: 
    - 
      name: Checkout Repo
      id: checkout_repo
      uses: actions/checkout@v4
      with:
        repository: ${{ github.repository }}
        ref: ${{ github.ref }}
        token: ${{ secrets.GITHUB_TOKEN }}
        
    - 
      name: Scan Pipeline Vunerability
      id: scan_pipeline
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'fs'
        scan-ref: '.'
        ignore-unfixed: true
        format: 'table'
        output: 'trivy-report.txt'
        exit-code: '1'
        severity: 'CRITICAL,HIGH'
    -
      name: Display Trivy Report
      run: cat trivy-report.txt  
    -
      name: Report Failure Messgae
      id: report_failure
      if: ${{ failure() }}
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_TEST}}
        SLACK_TITTLE: 'Pipeline Scan Failed'
        SLACK_MESSAGE: 'FAILED TRIVY SCAN'

    -   
      name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    -
      name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    -
      name: Build and Push
      uses: docker/build-push-action@v5
      with:
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/trivy-action:latest

    
    -
      name: Digitally Sign Docker Image
      uses: sigstore/cosign-installer@main   

    - name: Slack Notification
      id: slack_notification
      uses: slackapi/slack-github-action@v1.24.0
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_CHANNEL: ${{ secrets.SLACK_CHANNEL }}
        SLACK_USERNAME: ${{ secrets.SLACK_USERNAME }}
    

    - name: Build and push container
      id : build_and_push
      uses: docker/setup-qemu-action@v3
      


    - name: Upload Trivy Report
      id: upload_trivy_report
      uses: actions/upload-artifact@v2
      with:
        name: trivy-report
        path: trivy-report.txt
      env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_TEST}}