name: SLACK_NOTIFICATION

on: 
  push:

jobs:
  SlackAlert: 
    runs-on: ubuntu-latest
    
    steps: 
    - name: checkout repo
      id: checkout_repo
      uses: actions/checkout@v4
      with:
        ref: ${{ github.ref }}
