name: SLACK_NOTIFICATION

on: 
  push:
    branches: 
      - 'v[0-9]+.[0-9]+'
      - master
    
jobs:
  SLACK_NOTIFICATION: 
    if: ${{!startsWith(github.event.head_commit.message, '#NORUN')}} 
    runs-on: ubuntu-latest
    
    steps: 
    - 
      name: Checkout Repo
      id: checkout_repo
      uses: actions/checkout@v4
      with:
        repository: ${{ github.repository }}
        ref: ${{ github.ref }}
        token: ${{ secrets.GITHUB_TOKEN }}    
    - 
      name: Scan Pipeline Vunerability
      id: scan_pipeline
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'fs'
        scan-ref: '.'
        ignore-unfixed: true
        format: 'table'
        output: 'trivy-report.txt'
        severity: 'CRITICAL'
    - 
      name: Display Trivy Report
      run: cat trivy-report.txt
    -
      name: Set up QEMU
      if: steps.scan_pipeline.outcome == 'success'
      uses: docker/setup-qemu-action@v3
    -
      name: Set up Docker Buildx
      if: steps.scan_pipeline.outcome == 'success'
      uses: docker/setup-buildx-action@v3
    -
      name: Login to Docker Hub
      if: steps.scan_pipeline.outcome == 'success'
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    -
      name: Build and Push
      id: docker_build
      if: steps.scan_pipeline.outcome == 'success'
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: jmx139/go-fortune_jmx:${{ github.sha }}
    - 
      name: Install Cosign
      if: steps.scan_pipeline.outcome == 'success'
      uses: sigstore/cosign-installer@v3.1.1
      with:
        cosign-release: 'v2.2.0'
    - 
      name: Check install
      if: steps.scan_pipeline.outcome == 'success'
      run: cosign version
    - 
      name: Cosign Key
      if: steps.scan_pipeline.outcome == 'success'
      run: echo "${{ secrets.COSIGN_PRIVATE_KEY }}"  > cosign.key
    -
      name: Sign Image
      if: steps.scan_pipeline.outcome == 'success'
      run: cosign sign --yes --key cosign.key docker.io/jmx139/go-fortune_jmx@${{ steps.docker_build.outputs.digest }}
      env:
        COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}
        
        digest: ${{ steps.docker_build.outputs.digest }}
    -
      name : Verify Singature
      if: steps.scan_pipeline.outcome == 'success'
      run: cosign verify --key cosign.pub docker.io/jmx139/go-fortune_jmx@${{ steps.docker_build.outputs.digest }}
      env:
        COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}
        COSIGN_PUBLIC_KEY: ${{ secrets.COSIGN_PUBLIC_KEY }}
        digest: ${{ steps.docker_build.outputs.digest }}
    -
      name: Report Success Messgae
      if: steps.scan_pipeline.outcome == 'success'
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_SUBMISSION }}
        SLACK_TITLE: 'Pipeline Scan SUCCESSED'
        SLACK_MESSAGE: |
          NAME: JIANG MIN XUAN
          MATRICULATION: A0285995B
          EMAIL: E1221807@u.nus.edu
          GIT: https://github.com/MinXuanJ/CI-CD_Jmx1
          IMAGE: https://hub.docker.com/repository/docker/jmx139/go-fortune_jmx/general
  
      
          