name: SLACK_NOTIFICATION_FAIL

on: 
  push:
    branches: 
      - 'v[0-9]+.[0-9]+'
      - master
    
jobs:
  SLACK_NOTIFICATION: 
    if: ${{!startsWith(github.event.head_commit.message, '#NORUN')}} 
    runs-on: ubuntu-latest
    
    steps: 
    - 
      name: Checkout Repo
      id: checkout_repo
      uses: actions/checkout@v4
      with:
        repository: ${{ github.repository }}
        ref: ${{ github.ref }}
        token: ${{ secrets.GITHUB_TOKEN }}       
    - 
      name: Scan Pipeline Vunerability
      id: scan_pipeline
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'fs'
        scan-ref: '.'
        ignore-unfixed: true
        format: 'table'
        output: 'trivy-report.txt'
        severity: 'HIGH'
    -
      name: Report Failure Messgae
      id: report_failure
      
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_TEST}}
        SLACK_TITLE: 'Pipeline Scan Failed'
        SLACK_MESSAGE: 'FAILED TRIVY SCAN'
    - 
      name: Upload Trivy Report
      id: upload_trivy_report
      if: always()
      uses: MeilCli/slack-upload-file@v3 
      with:
        slack_token: ${{ secrets.SLACK_BOT_TOKEN}}
        channel_id: ${{ secrets.SLACK_CHANNELID_TEST}}
        file_path: 'trivy-report.txt'
        initial_comment: 'Report by Jmx'
      
          